name: Arduino CI with Static Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Arduino CLI
        uses: arduino/setup-arduino-cli@v1
      - name: Install board platform
        run: arduino-cli core install arduino:avr
      - name: Install libraries
        run: |
          arduino-cli lib install "LiquidCrystal_I2C"
          arduino-cli lib install "Finite-State"
      - name: Compile sketch
        run: arduino-cli compile --fqbn arduino:avr:uno TissueProcessor/TissueProcessor.ino